config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: 'homes#index'

  devise_for :users, skip: :all
  devise_scope :user do
    get :login, to: 'devise/sessions#new', as: :new_user_session
    post :login, to: 'devise/sessions#create', as: :user_session
  end

  namespace :api do
    namespace :v1 do
      resources :users do
        collection do
          delete :sessions, to: 'users/sessions#destroy'
        end
      end

      resources :roles, only: %i[index]
    end
  end
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :validatable, :lockable, :trackable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/base_friendly_id.rb
module BaseFriendlyId
  extend ActiveSupport::Concern

  included do
    include FriendlyId
    friendly_id :uuid
    before_create { self.uuid = SecureRandom.uuid }
  end
end

app/models/user.rb
class User < ApplicationRecord
  include BaseFriendlyId

  # Include default devise modules. Others available are:
  # :registerable, :recoverable, :rememberable
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :validatable, :lockable, :trackable

  has_one :user_info, autosave: true, dependent: :destroy
  has_many :user_roles, dependent: :destroy

  validates :user_info, presence: true

  def role?(name)
    user_roles.exists?(name: name)
  end

  def roles
    user_roles.map { |user_role| user_role.name.to_sym }
  end

  def roles_i18n
    user_roles.map(&:name_i18n)
  end

  def replace_roles!(names)
    source = roles.to_set
    dest = names.map(&:to_sym).to_set

    user_roles.where(name: (source - dest)).each(&:destroy!) # rubocop:disable Rails/FindEach:

    (dest - source).each do |name|
      user_roles.create!(name: name)
    end

    user_roles.reload

    dest
  end
end

app/models/user_info.rb
class UserInfo < ApplicationRecord
  include BaseFriendlyId

  belongs_to :user

  validates :name, presence: true
end

app/models/user_role.rb
class UserRole < ApplicationRecord
  include BaseFriendlyId

  NAME_VALUES = {
    role_management: 0,
    user_management: 1,
  }.freeze
  NAMES = NAME_VALUES.keys.map(&:to_s).freeze

  enum name: NAME_VALUES

  belongs_to :user

  validates :name, presence: true, inclusion: { in: NAMES }
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AuthenticatedController
  def index
    render json: { users: User.all }
  end
end

app/controllers/api/v1/base_controller.rb
# rubocop:disable Naming/VariableNumber
class Api::V1::BaseController < AuthenticatedController
  rescue_from StandardError,                      with: :_render_500
  rescue_from ActiveRecord::RecordInvalid,        with: :_render_422
  rescue_from ActiveRecord::RecordNotFound,       with: :_render_404
  rescue_from ActionController::RoutingError,     with: :_render_404
  rescue_from ActionController::ParameterMissing, with: :_render_400

  private

  def routing_error
    raise ActionController::RoutingError, params[:path]
  end

  def _render_500(exception = nil)
    @rescued_exception = exception
    logger.error exception.message
    exception.backtrace.each { |line| logger.error line }
    render json: { error: '500 internal server errror' }, status: :internal_server_error
  end

  def _render_422(exception = nil)
    @rescued_exception = exception
    logger.info exception.message
    logger.info exception.record.inspect
    exception.backtrace.each { |line| logger.info line }
    render json: { messages: exception.record.errors.full_messages }, status: :unprocessable_entity
  end

  def _render_404(exception = nil)
    @rescued_exception = exception
    logger.info exception.message
    exception.backtrace.each { |line| logger.info line }
    render json: { error: '404 not found' }, status: :not_found
  end

  def _render_400(exception = nil)
    @rescued_exception = exception
    logger.info exception.message
    exception.backtrace.each { |line| logger.info line }
    render json: { error: '400 bad request' }, status: :bad_request
  end
end
# rubocop:enable Naming/VariableNumber

app/controllers/api/v1/roles_controller.rb
class Api::V1::RolesController < Api::V1::BaseController
  def index; end
end

app/controllers/api/v1/users/sessions_controller.rb
class Api::V1::Users::SessionsController < Api::V1::BaseController
  def destroy
    sign_out current_user
    render json: {}
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::BaseController
  before_action :set_user, only: %i[show update destroy]

  def index
    @users = User.eager_load(:user_info).includes(:user_roles)
  end

  def show; end

  def create
    @user = User.new(user_params)
    @user.build_user_info(user_info_params)

    User.transaction do
      @user.save!
      @user.replace_roles!(user_role_params[:roles])
    end

    render :show
  end

  def update
    @user.assign_attributes(user_params)
    @user.user_info.assign_attributes(user_info_params)

    User.transaction do
      @user.save!
      @user.replace_roles!(user_role_params[:roles])
    end

    render :show
  end

  def destroy
    @user.destroy!
  end

  private

  def set_user
    @user = User.friendly.find(params[:id])
  end

  def user_params
    params.require(:user).permit(
      :email,
      :password,
      :password_confirmation,
    )
  end

  def user_info_params
    params.require(:user).permit(
      :name,
    )
  end

  def user_role_params
    params.require(:user).permit(
      roles: [],
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def append_info_to_payload(payload)
    super
    return if @rescued_exception.blank?

    payload[:exception_object] ||= @rescued_exception
    payload[:exception] ||= [@rescued_exception.class, @rescued_exception.message]
  end
end

app/controllers/authenticated_controller.rb
class AuthenticatedController < ApplicationController
  before_action :authenticate_user!

  def append_info_to_payload(payload)
    super
    payload[:user_id] = current_user&.id
  end
end

app/controllers/homes_controller.rb
class HomesController < AuthenticatedController
  def index
    render layout: false
  end
end

app/controllers/users_controller.rb
class UsersController < AuthenticatedController
  def index
    @users = User.all
                 .eager_load(:user_info)
                 .includes(:user_roles)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/homes/index.html.slim
doctype html
html
  head
    title
      | RailsTemplate
    = csrf_meta_tags
    = csp_meta_tag
    = javascript_pack_tag 'application'
    = stylesheet_pack_tag 'application'
  body
    #app

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | RailsTemplate
    = csrf_meta_tags
    = csp_meta_tag
    = favicon_link_tag '/favicon.ico'
    meta name='robots' content='noindex'
    meta name='viewport' content='width=device-width, initial-scale=1'

    = stylesheet_link_tag 'application', media: 'all'
    = javascript_pack_tag 'application'

    link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/bulma@0.9.0/css/bulma.min.css'
  body
    nav.navbar role='navigation' aria-label='main navigation'
      .navbar-brand
        a href='/'
          h1.title Rails Template
      - if user_signed_in?
        .navbar-menu
          .navbar-start
            = link_to 'Users', users_path, class: 'navbar-item'
          .navbar-end
            .navbar-item
              .buttons
                = link_to 'Logout', destroy_user_session_path, method: :delete, class: 'button is-light'
    section.section
      .container
        = yield

app/views/users/index.html.slim
table.table.is-striped.is-fullwidth
  thead
    tr
      th Email
      th name
      th roles
  tbody
    - @users.each do |user|
      tr
        td = user.email
        td = user.user_info.name
        td
          - user.user_roles.each do |user_role|
            div = user_role.role_i18n

app/views/users/shared/_error_messages.html.slim
- if resource.errors.any?
  #error_explanation
    h2
      = I18n.t("errors.messages.not_saved",
      -                  count: resource.errors.count,
      -                  resource: resource.class.model_name.human.downcase)
    ul
      - resource.errors.full_messages.each do |message|
        li
          = message

app/views/users/shared/_links.html.slim
- if controller_name != 'sessions'
  = link_to "Log in", new_session_path(resource_name)
  br
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  br
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "Forgot your password?", new_password_path(resource_name)
  br
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  br
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  br
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider)
    br